language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11

end:
  - JULIA_COPY_STACKS=1

matrix:
  allow_failures:
    - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  email: false
