language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11

matrix:
  allow_failures:
    - julia_version: nightly
    - julia_version: 1.2

notifications:
  email: false
